# Generated by Django 6.1 on 2026-08-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_sentsms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentSMS',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='recipients',
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
