# Generated by Django 6.1 on 2026-08-24 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_smsmessage_recipients'),
        ('sms', '0003_delete_sentsms_remove_smsmessage_recipients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sms.smsmessage')),
            ],
        ),
    ]
