"""
Django settings for iwachu_system project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
import os

from dotenv import load_dotenv
import dj_database_url

# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# ENVIRONMENT VARIABLES
# =========================================================

# Soma .env iliyopo kwenye folder yenye manage.py
load_dotenv(BASE_DIR / ".env")


# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-development-key"
)

DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".onrender.com",
]
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
]

if os.getenv("RENDER_EXTERNAL_HOSTNAME"):
    ALLOWED_HOSTS.append(
        os.getenv("RENDER_EXTERNAL_HOSTNAME")
    )

# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [

    # Admin theme
    "unfold",

    # Django applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Our applications
    "members",
    "sms",
]
# =========================================================
# UNFOLD ADMIN THEME
# =========================================================

UNFOLD = {

    "SITE_TITLE": "IWACHU IMSAMBARA",

    "SITE_HEADER": "IWACHU IMSAMBARA",

    "SITE_SUBHEADER": "Member Management & SMS System",

    "SITE_SYMBOL": "groups",

    "SHOW_HISTORY": True,

    "SHOW_VIEW_ON_SITE": True,

    "SHOW_BACK_BUTTON": True,
    "DASHBOARD_CALLBACK":
    "iwachu_system.admin_dashboard.dashboard_callback",

    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },

    "TABS": [
        {
            "models": [
                "members.member",
            ],
            "items": [
                {
                    "title": "Members",
                    "icon": "groups",
                    "link": "/admin/members/member/",
                },
            ],
        },
        {
            "models": [
                "sms.smsmessage",
            ],
            "items": [
                {
                    "title": "SMS Messages",
                    "icon": "sms",
                    "link": "/admin/sms/smsmessage/",
                },
            ],
        },
    ],
}


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
   'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = 'iwachu_system.urls'


# =========================================================
# TEMPLATES
# =========================================================
TEMPLATES = [

    {
        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / "templates"
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = 'iwachu_system.wsgi.application'


# =========================================================
# DATABASE
# =========================================================

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },

    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# =========================================================
# OLD SMS API
# =========================================================

# Hii unaweza kuiacha kama mfumo wako wa zamani bado
# una sehemu inayotumia SMS_API_KEY.

SMS_API_KEY = os.getenv('SMS_API_KEY')


# =========================================================
# TEXTBEE SMS GATEWAY
# =========================================================

# Muhimu:
# HAPA tunaweka majina ya variables yaliyopo kwenye .env.
# Hatuweki API key yenyewe hapa.

TEXTBEE_API_KEY = os.getenv('TEXTBEE_API_KEY')

TEXTBEE_DEVICE_ID = os.getenv('TEXTBEE_DEVICE_ID')


# =========================================================
# EMAIL
# =========================================================

EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend'
)


# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'