# Generated by Django 6.1 on 2026-08-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(max_length=100)),
                ('simu', models.CharField(max_length=20, unique=True)),
                ('kitongoji', models.CharField(blank=True, max_length=100)),
                ('jinsia', models.CharField(blank=True, max_length=20)),
                ('tarehe_ya_usajili', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
