# Generated by Django 6.1 on 2026-08-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_smsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
