# Generated by Django 6.1 on 2026-08-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_smsmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='sms_messages', to='members.member'),
        ),
    ]
